name: Export and Publish Lecture PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'lectures/**'
      - 'package.json'
      - 'package-lock.json'
      - 'bun.lock'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'scripts/export-pdfs.mjs'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Do not enable npm caching when no lockfile is present

      - name: Install dependencies
        run: |
          npm i

      - name: Install Playwright Chromium deps
        run: |
          npx playwright install --with-deps chromium || true

      - name: Export PDFs and registry
        run: |
          node scripts/export-pdfs.mjs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist-pdf

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


